complete(?) HW_13
9Archik9/py94 pull request #6
Opened 2023-12-05 16:12 UTC by 9Archik9

Создать класс DataStorage. 
Конструктор принимает на вход путь к файлу json, который в дальнейшем нельзя изменить снаружи. 
Так же определяем атрибуты 
status - изначально disconnected
content - изначально None

Реализовать методы
_create_storage создает файл по принятому в конструктор пути и возвращает экземпляр файла.
connect возвращает экземпляр файла (open), меняет статус на connected и присваивает в атрибут content - содержимое файла если файл найден, если нет, вызывает метод _create и делает то же самое.
disconnect берет файл, закрывает его и выводит в консоль сообщение об этом

Создать класс DataStorageWrite
Переопределить методы connect и _create таким образом, что бы файл был готов к добавлению контента. При этом content так же выдавал содержимое файла.
Определить метод append который принимает строку, которую мы записываем в файл. После disconnect - мы можем наблюдать обновленный файл.

2023-12-07 05:41 UTC, nicilytop-tms requested changes

2023-12-07 05:41 UTC, nicilytop-tms commented on Lessons/Lesson_13/Homework/app.py
PEP8

2023-12-07 12:54 UTC, 9Archik9 commented on Lessons/Lesson_13/Homework/app.py
Refactor

2023-12-08 13:58 UTC, nicilytop-tms approved these changes
good

2023-12-08 18:01 UTC, merged