lesson_16_sql
9Archik9/py94 pull request #9
Opened 2023-12-17 00:37 UTC by 9Archik9

ДЗ:

Написать sql код в котором:

Создать базу данных с сущностями:

Пользователь
Потребление (прием пищи)
Продукт

Создать ограничения для всех полей + в комментариях обосновать почему и зачем такие-то ограничения поставлены

commit 2:
"I added a blank line at the end because git was swearing and showing a red circle."
is it necessary!?

2023-12-18 08:00 UTC, nicilytop-tms requested changes

2023-12-18 08:00 UTC, nicilytop-tms commented on Lessons/Lesson_16/Homework/meal_database.sql
> +    food_intake CHAR(5) CONSTRAINT must_be_time_format CHECK (food_intake LIKE '__:__') NOT NULL,
hmm 🤔 only hours and minutes? .. why? I cant see what user ate yesterday?..

2023-12-18 08:00 UTC, nicilytop-tms commented on Lessons/Lesson_16/Homework/meal_database.sql
Where others two tables? Product and User I mean?

2023-12-18 16:02 UTC, 9Archik9 commented
update full hw

2023-12-19 06:24 UTC, nicilytop-tms approved these changes
Nice job

2023-12-19 06:24 UTC, nicilytop-tms commented on Lessons/Lesson_16/Homework/NutritionDatabase.sql
> +     there are only two genders 🙂
🥲

2023-12-19 06:24 UTC, nicilytop-tms commented on Lessons/Lesson_16/Homework/NutritionDatabase.sql
> +    ConsumptionID SERIAL PRIMARY KEY,
Just `id`.. it is overhead call field `ConsumptionID` into `Consumption` table..
Better to imagine table like an Object  -> `Consumption.id`

2023-12-19 12:59 UTC, merged